config/routes.rb
Rails.application.routes.draw do
  resources :books
  devise_for :users
  root 'pages#home'

  get 'dashboard' => 'pages#dashboard'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all.where(availability: true)
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = current_user.books.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:name, :author, :description, :price, :availability)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:dashboard]
  def home
    if current_user
      redirect_to books_path
    end
  end

    def dashboard
      @books = current_user.books
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/books/_book.html.erb
 <div class = 'col-md-4'>
    <div class = 'thumbnail'>
    <%= image_tag 'cover-web.png', class: 'img-responsive' %></div>
    <div class = 'caption'>
    <p><strong><%= link_to book.name, book_path(book) %></strong></p>
    <p>$<%= book.price/100 %></p>
    </div>
</div>

app/views/books/_form.html.erb
<%= simple_form_for(@book, html: {class: 'form-signin'}) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  
    <%= f.input :name, required: true, label: false, placeholder: 'Book Name' %>
    <%= f.input :author, required: true, label: false, placeholder: 'Book Author' %>
    <%= f.input :description, required: true, label: false, placeholder: 'Book Description' %>
    <%= f.input :price, required: true, label: false, placeholder: 'Price' %>
    <%= f.input :availability %>
  
    <%= f.button :submit, class: 'btn btn-primary btn-block' %>
  
<% end %>

app/views/books/edit.html.erb
<h1 class = 'text-center'>Edit Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<div class = 'row'><%= render @books %></div>



<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1 class = 'text-center'>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<div class="row">
    <div class="col-md-6"> <%= image_tag 'cover-web.png', class: 'img-fluid' %></div>
    <div class="col-md-6"> <h3><%= @book.name %> by <%= @book.author %></h3>
     <p><%= @book.description %></p>
     <p><strong>$<%= @book.price/100 %></strong></p></div>
  </div>
</div>
</div>


<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light" style="background-color: #f8f9fa;">
  
  <%= link_to '<i class="fas fa-book"></i> eBook Store' .html_safe, root_path, class: 'navbar-brand' %>
  
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Books', books_path %></li>
        <% if current_user %>
        <li><%= link_to 'Profile', edit_user_registration_path %></li>
        <li><%= link_to 'Dashboard', dashboard_path %>    </li>
        <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to 'Log In', new_user_session_path %></li>
        <% end %>
    </ul>
  </div>
</nav>
  
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <div class= 'container'>
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/dashboard.html.erb
<h1>Dashboard</h1>

<div class = 'row'>
    <div class = 'col-md-4'>
      <h3>Books
      <%= link_to 'Add Book', new_book_path, class: 'btn btn-primary btn-sm' %>
      </h3>
      <table class="table table-sm">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Name</th>
      <th scope="col">Available</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  <% @books.each do |book| %>
    <tr>
      <td><%= book.id %></td>
      <td><%= link_to book.name, book_path(book) %></td>
      <td><%= book.availability %></td>
      <td><%= link_to 'Edit', edit_book_path(book) %></td>
    </tr>
    <% end %>
   
  </tbody>
</table>
    </div>

   <div class = 'col-md-4'>
      <h3>Purchases</h3>
      <table class="table table-sm">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Name</th>
      <th scope="col">Available</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    
  </tbody>
</table>
    </div>
    <div class = 'col-md-4'>
      <h3>Sales</h3>
      <table class="table table-sm">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Name</th>
      <th scope="col">Available</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    
  </tbody>
</table>
    </div>
  </div>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h1 class="display-4"><i class="fas fa-book" aria-hidden="true"></i> Welcome to the Great Escapes eBooks store!</h1>
  <p class="lead">A marketplace for buyers, sellers, and lovers of books.</p>
  
  <%=link_to 'Books', books_path, class: 'btn btn-primary btn-lg' %>
  <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
</div>